basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a sample authentication service API using Swagger.
  title: Authentication Service API
  version: "1.0"
paths: {}
swagger: "2.0"
